name = "Ji"
license = "MIT"
licenselink = "https://github.com/yourusername/Ji/blob/main/LICENSE"
description = "一个简洁现代的 Hugo 主题，适合个人博客使用。"
homepage = "https://github.com/yourusername/Ji"
tags = [
  "blog",
  "responsive",
  "dark-mode",
  "modern",
  "minimal"
]
features = [
  "responsive",
  "dark-mode",
  "syntax-highlighting",
  "search",
  "rss"
]
min_version = "1.100.0"

[author]
  name = "jizuiba"
  homepage = "https://github.com/jizuiba"
