# 最小配置示例
baseURL = "https://example.com"
languageCode = "zh-cn"
title = "我的博客"
theme = "Ji"

[params]
  title = "我的博客"
  description = "我的个人博客"
  author = "您的名字"
  darkMode = true
  search = true
  syntaxHighlighting = true

[[menu.main]]
  name = "首页"
  url = "/"
  weight = 1

[[menu.main]]
  name = "文章"
  url = "/posts"
  weight = 2

[markup.highlight]
  style = "github"
  codeFences = true
  lineNumbersInTable = false # 表格中的行号
  noClasses = false          # 使用CSS类

[outputs]
  home = ["HTML", "RSS", "JSON"]
  page = ["HTML"]
  section = ["HTML", "RSS"]
  taxonomy = ["HTML", "RSS"]
